# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/noah/Dropbox/Cornell_Classes/2015sp/ECE4250/project1/ECE4250-Project1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/noah/Dropbox/Cornell_Classes/2015sp/ECE4250/project1/ECE4250-Project1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/noah/Dropbox/Cornell_Classes/2015sp/ECE4250/project1/ECE4250-Project1/CMakeFiles /home/noah/Dropbox/Cornell_Classes/2015sp/ECE4250/project1/ECE4250-Project1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/noah/Dropbox/Cornell_Classes/2015sp/ECE4250/project1/ECE4250-Project1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named aesthetic

# Build rule for target.
aesthetic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aesthetic
.PHONY : aesthetic

# fast build rule for target.
aesthetic/fast:
	$(MAKE) -f CMakeFiles/aesthetic.dir/build.make CMakeFiles/aesthetic.dir/build
.PHONY : aesthetic/fast

#=============================================================================
# Target rules for targets named descript

# Build rule for target.
descript: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 descript
.PHONY : descript

# fast build rule for target.
descript/fast:
	$(MAKE) -f CMakeFiles/descript.dir/build.make CMakeFiles/descript.dir/build
.PHONY : descript/fast

#=============================================================================
# Target rules for targets named predict

# Build rule for target.
predict: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 predict
.PHONY : predict

# fast build rule for target.
predict/fast:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/build
.PHONY : predict/fast

#=============================================================================
# Target rules for targets named train

# Build rule for target.
train: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 train
.PHONY : train

# fast build rule for target.
train/fast:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/build
.PHONY : train/fast

Aesthetics.o: Aesthetics.cpp.o
.PHONY : Aesthetics.o

# target to build an object file
Aesthetics.cpp.o:
	$(MAKE) -f CMakeFiles/aesthetic.dir/build.make CMakeFiles/aesthetic.dir/Aesthetics.cpp.o
.PHONY : Aesthetics.cpp.o

Aesthetics.i: Aesthetics.cpp.i
.PHONY : Aesthetics.i

# target to preprocess a source file
Aesthetics.cpp.i:
	$(MAKE) -f CMakeFiles/aesthetic.dir/build.make CMakeFiles/aesthetic.dir/Aesthetics.cpp.i
.PHONY : Aesthetics.cpp.i

Aesthetics.s: Aesthetics.cpp.s
.PHONY : Aesthetics.s

# target to generate assembly for a file
Aesthetics.cpp.s:
	$(MAKE) -f CMakeFiles/aesthetic.dir/build.make CMakeFiles/aesthetic.dir/Aesthetics.cpp.s
.PHONY : Aesthetics.cpp.s

KMeansCluster.o: KMeansCluster.cpp.o
.PHONY : KMeansCluster.o

# target to build an object file
KMeansCluster.cpp.o:
	$(MAKE) -f CMakeFiles/aesthetic.dir/build.make CMakeFiles/aesthetic.dir/KMeansCluster.cpp.o
.PHONY : KMeansCluster.cpp.o

KMeansCluster.i: KMeansCluster.cpp.i
.PHONY : KMeansCluster.i

# target to preprocess a source file
KMeansCluster.cpp.i:
	$(MAKE) -f CMakeFiles/aesthetic.dir/build.make CMakeFiles/aesthetic.dir/KMeansCluster.cpp.i
.PHONY : KMeansCluster.cpp.i

KMeansCluster.s: KMeansCluster.cpp.s
.PHONY : KMeansCluster.s

# target to generate assembly for a file
KMeansCluster.cpp.s:
	$(MAKE) -f CMakeFiles/aesthetic.dir/build.make CMakeFiles/aesthetic.dir/KMeansCluster.cpp.s
.PHONY : KMeansCluster.cpp.s

ROTAverage.o: ROTAverage.cpp.o
.PHONY : ROTAverage.o

# target to build an object file
ROTAverage.cpp.o:
	$(MAKE) -f CMakeFiles/aesthetic.dir/build.make CMakeFiles/aesthetic.dir/ROTAverage.cpp.o
.PHONY : ROTAverage.cpp.o

ROTAverage.i: ROTAverage.cpp.i
.PHONY : ROTAverage.i

# target to preprocess a source file
ROTAverage.cpp.i:
	$(MAKE) -f CMakeFiles/aesthetic.dir/build.make CMakeFiles/aesthetic.dir/ROTAverage.cpp.i
.PHONY : ROTAverage.cpp.i

ROTAverage.s: ROTAverage.cpp.s
.PHONY : ROTAverage.s

# target to generate assembly for a file
ROTAverage.cpp.s:
	$(MAKE) -f CMakeFiles/aesthetic.dir/build.make CMakeFiles/aesthetic.dir/ROTAverage.cpp.s
.PHONY : ROTAverage.cpp.s

Sizer.o: Sizer.cpp.o
.PHONY : Sizer.o

# target to build an object file
Sizer.cpp.o:
	$(MAKE) -f CMakeFiles/aesthetic.dir/build.make CMakeFiles/aesthetic.dir/Sizer.cpp.o
.PHONY : Sizer.cpp.o

Sizer.i: Sizer.cpp.i
.PHONY : Sizer.i

# target to preprocess a source file
Sizer.cpp.i:
	$(MAKE) -f CMakeFiles/aesthetic.dir/build.make CMakeFiles/aesthetic.dir/Sizer.cpp.i
.PHONY : Sizer.cpp.i

Sizer.s: Sizer.cpp.s
.PHONY : Sizer.s

# target to generate assembly for a file
Sizer.cpp.s:
	$(MAKE) -f CMakeFiles/aesthetic.dir/build.make CMakeFiles/aesthetic.dir/Sizer.cpp.s
.PHONY : Sizer.cpp.s

Transforms.o: Transforms.cpp.o
.PHONY : Transforms.o

# target to build an object file
Transforms.cpp.o:
	$(MAKE) -f CMakeFiles/aesthetic.dir/build.make CMakeFiles/aesthetic.dir/Transforms.cpp.o
.PHONY : Transforms.cpp.o

Transforms.i: Transforms.cpp.i
.PHONY : Transforms.i

# target to preprocess a source file
Transforms.cpp.i:
	$(MAKE) -f CMakeFiles/aesthetic.dir/build.make CMakeFiles/aesthetic.dir/Transforms.cpp.i
.PHONY : Transforms.cpp.i

Transforms.s: Transforms.cpp.s
.PHONY : Transforms.s

# target to generate assembly for a file
Transforms.cpp.s:
	$(MAKE) -f CMakeFiles/aesthetic.dir/build.make CMakeFiles/aesthetic.dir/Transforms.cpp.s
.PHONY : Transforms.cpp.s

descript.o: descript.cpp.o
.PHONY : descript.o

# target to build an object file
descript.cpp.o:
	$(MAKE) -f CMakeFiles/descript.dir/build.make CMakeFiles/descript.dir/descript.cpp.o
.PHONY : descript.cpp.o

descript.i: descript.cpp.i
.PHONY : descript.i

# target to preprocess a source file
descript.cpp.i:
	$(MAKE) -f CMakeFiles/descript.dir/build.make CMakeFiles/descript.dir/descript.cpp.i
.PHONY : descript.cpp.i

descript.s: descript.cpp.s
.PHONY : descript.s

# target to generate assembly for a file
descript.cpp.s:
	$(MAKE) -f CMakeFiles/descript.dir/build.make CMakeFiles/descript.dir/descript.cpp.s
.PHONY : descript.cpp.s

predict.o: predict.cpp.o
.PHONY : predict.o

# target to build an object file
predict.cpp.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/predict.cpp.o
.PHONY : predict.cpp.o

predict.i: predict.cpp.i
.PHONY : predict.i

# target to preprocess a source file
predict.cpp.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/predict.cpp.i
.PHONY : predict.cpp.i

predict.s: predict.cpp.s
.PHONY : predict.s

# target to generate assembly for a file
predict.cpp.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/predict.cpp.s
.PHONY : predict.cpp.s

train.o: train.cpp.o
.PHONY : train.o

# target to build an object file
train.cpp.o:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/train.cpp.o
.PHONY : train.cpp.o

train.i: train.cpp.i
.PHONY : train.i

# target to preprocess a source file
train.cpp.i:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/train.cpp.i
.PHONY : train.cpp.i

train.s: train.cpp.s
.PHONY : train.s

# target to generate assembly for a file
train.cpp.s:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/train.cpp.s
.PHONY : train.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... aesthetic"
	@echo "... descript"
	@echo "... edit_cache"
	@echo "... predict"
	@echo "... rebuild_cache"
	@echo "... train"
	@echo "... Aesthetics.o"
	@echo "... Aesthetics.i"
	@echo "... Aesthetics.s"
	@echo "... KMeansCluster.o"
	@echo "... KMeansCluster.i"
	@echo "... KMeansCluster.s"
	@echo "... ROTAverage.o"
	@echo "... ROTAverage.i"
	@echo "... ROTAverage.s"
	@echo "... Sizer.o"
	@echo "... Sizer.i"
	@echo "... Sizer.s"
	@echo "... Transforms.o"
	@echo "... Transforms.i"
	@echo "... Transforms.s"
	@echo "... descript.o"
	@echo "... descript.i"
	@echo "... descript.s"
	@echo "... predict.o"
	@echo "... predict.i"
	@echo "... predict.s"
	@echo "... train.o"
	@echo "... train.i"
	@echo "... train.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

